# Generated by Django 6.0 on 2025-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'б/у')], max_length=20, verbose_name='Состояние'),
        ),
    ]
