# Generated by Django 6.0 on 2026-01-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.CharField(help_text='Например: Бытовая техника, Конспекты, Одежда и т.д.', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название объявления'),
        ),
        migrations.CreateModel(
            name='DealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='waiting', max_length=10)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
