# Generated by Django 6.0 on 2026-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_address_alter_ads_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealrequest',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
