# Generated by Django 6.0 on 2026-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ads', models.PositiveIntegerField(default=0, verbose_name='Всего объявлений')),
                ('active_ads', models.PositiveIntegerField(default=0, verbose_name='Активных объявлений')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Всего пользователей')),
                ('total_chats', models.PositiveIntegerField(default=0, verbose_name='Всего чатов')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Всего сообщений')),
                ('total_favorites', models.PositiveIntegerField(default=0, verbose_name='Добавлено в избранное')),
                ('total_deals', models.PositiveIntegerField(default=0, verbose_name='Всего сделок')),
                ('completed_deals', models.PositiveIntegerField(default=0, verbose_name='Завершенных сделок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистика сайта',
                'ordering': ['-updated_at'],
            },
        ),
    ]
