# Generated by Django 6.0 on 2026-01-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_sitestatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='completed_deals',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='total_deals',
        ),
        migrations.DeleteModel(
            name='DealRequest',
        ),
    ]
