# Generated by Django 6.0 on 2025-12-23 17:31

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Role.objects.get_or_create(name='seller')
    Role.objects.get_or_create(name='buyer')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]
