# Generated by Django 6.0 on 2025-12-25 09:08

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Role.objects.get_or_create(name='seller')
    Role.objects.get_or_create(name='buyer')

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20251223_2031'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]
