# Generated by Django 6.0 on 2025-12-28 11:26
from django.db import migrations


def update_role_names(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Role.objects.filter(name='seller').update(name='Продавец')
    Role.objects.filter(name='buyer').update(name='Покупатель')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20251225_1208'),
    ]

    operations = [
        migrations.RunPython(update_role_names),
    ]
